// Package harvester provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package harvester

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// GetFederationRelationshipsParams defines parameters for GetFederationRelationships.
type GetFederationRelationshipsParams struct {
	// filter relationships by spireServer
	SpireServer *string `form:"spireServer,omitempty" json:"spireServer,omitempty"`

	// filter relationships by status
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// filter relationships by status
	FederationGroupId *int64 `form:"federationGroupId,omitempty" json:"federationGroupId,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /FederationRelationship)
	GetFederationRelationships(ctx echo.Context, params GetFederationRelationshipsParams) error

	// (GET /FederationRelationship/{relationshipID})
	GetRelationshipbyID(ctx echo.Context, relationshipID int64) error

	// (PUT /FederationRelationship/{relationshipID})
	UpdateFederatedRelationshipStatus(ctx echo.Context, relationshipID int64) error

	// (PUT /trustBundles/{trustBundleId})
	UpdateTrustBundle(ctx echo.Context, trustBundleId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFederationRelationships converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationRelationships(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFederationRelationshipsParams
	// ------------- Optional query parameter "spireServer" -------------

	err = runtime.BindQueryParameter("form", true, false, "spireServer", ctx.QueryParams(), &params.SpireServer)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spireServer: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "federationGroupId" -------------

	err = runtime.BindQueryParameter("form", true, false, "federationGroupId", ctx.QueryParams(), &params.FederationGroupId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter federationGroupId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationRelationships(ctx, params)
	return err
}

// GetRelationshipbyID converts echo context to params.
func (w *ServerInterfaceWrapper) GetRelationshipbyID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "relationshipID" -------------
	var relationshipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "relationshipID", runtime.ParamLocationPath, ctx.Param("relationshipID"), &relationshipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relationshipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRelationshipbyID(ctx, relationshipID)
	return err
}

// UpdateFederatedRelationshipStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateFederatedRelationshipStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "relationshipID" -------------
	var relationshipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "relationshipID", runtime.ParamLocationPath, ctx.Param("relationshipID"), &relationshipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relationshipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateFederatedRelationshipStatus(ctx, relationshipID)
	return err
}

// UpdateTrustBundle converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTrustBundle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trustBundleId" -------------
	var trustBundleId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "trustBundleId", runtime.ParamLocationPath, ctx.Param("trustBundleId"), &trustBundleId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trustBundleId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateTrustBundle(ctx, trustBundleId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/FederationRelationship", wrapper.GetFederationRelationships)
	router.GET(baseURL+"/FederationRelationship/:relationshipID", wrapper.GetRelationshipbyID)
	router.PUT(baseURL+"/FederationRelationship/:relationshipID", wrapper.UpdateFederatedRelationshipStatus)
	router.PUT(baseURL+"/trustBundles/:trustBundleId", wrapper.UpdateTrustBundle)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yWUW/bNhCA/wpxGLAXxfKaYhj01qBrprcgWZ+GPtDiyeZAkczx2FQz9N8HUlEjOfaa",
	"BUMWFAggSDrmPh6/O3kPjeu8s2g5QLUfCtC2dVDtQWFoSHvWzkIF765qwU5sUMSASrSOhLaMJBvWdivu",
	"NO/Eb5I+Y2CksIICWLNBqODmqr7+VVyQVlsUZ+JSGqlIoxnDKcWLd1c1FJDuxmw/rdarNQwFOI9Weg0V",
	"nOdHBXjJu0QK5QdUSDLxXaPJ17DTPr3aIj/ewTVyJBuENEa041JUgmZLg3CtkGIEDpjohLaCdzijHp9D",
	"Rhuz1woquEQ+zhMyM8kOU2Gg+uOQq9UmlWAJsulF8JrwZsqmU+htROqhACu7VNllRGh22Mm079ZRJzkF",
	"MGm7TWfRe3y4H4biyRAsOYZT+aeXL5+6/VrrS3LR1+o4hbb889sHiGTsFgmG4VMBhME7GzDL9Ga9TpfG",
	"WUab5ZHeG93kFOWfIZHuZxk0Y5cX/kDYQgWrVfn1r3Fd52w5BodVLzuTVL5nkESyh2EYioM6bJGXRfgx",
	"iIkRcnQro+F/hflUusc00eIXj01qESRyqWYp6ETTlfs5ef1+ONmFaZdKsswTxFkUjrbS6r/y4mNdNU+z",
	"6ev332qnWqUuTj07R7qfXYRMGj+jmrRK0+TBquUmIDlyGzWhgoop4ssq9vyzOzTp1YlUgI9H3IheSUYh",
	"x5E79v84khdHuelFPpylKh/z4g/TYJ9rczNNkmeKM3K9lDK3EQNfONX/wwF9Obu7uztL//AskkHbOJUy",
	"/jcndp8zTOVwtJ0+/bkQKkl0oPbbx6dpnZjoX830YoqBL6JVBkO5n93VKo+so1p+9MZJJaT4/SH+hH7L",
	"iCfqljHEJq/6lm4L5O/SthPVGP7XaTqHen2f5aGA8Vfp6FkkAxXsmH1VlsY10uxc4Or8zfn6lxKGT8Pf",
	"AQAA///Q8Lb29AsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
