global:
  scrape_interval: 30s # Default 

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'galadriel-server'
    static_configs:
      - targets: ['localhost:8888']
