// Package api_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api_server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for FederationGroupStatus.
const (
	FederationGroupStatusActive   FederationGroupStatus = "active"
	FederationGroupStatusInactive FederationGroupStatus = "inactive"
)

// Defines values for FederationGroupMembershipStatus.
const (
	FederationGroupMembershipStatusActive   FederationGroupMembershipStatus = "active"
	FederationGroupMembershipStatusInactive FederationGroupMembershipStatus = "inactive"
)

// Defines values for FederationRelationshipStatus.
const (
	FederationRelationshipStatusActive   FederationRelationshipStatus = "active"
	FederationRelationshipStatusInactive FederationRelationshipStatus = "inactive"
	FederationRelationshipStatusInvited  FederationRelationshipStatus = "invited"
)

// Defines values for SpireServerStatus.
const (
	SpireServerStatusActive   SpireServerStatus = "active"
	SpireServerStatusInactive SpireServerStatus = "inactive"
	SpireServerStatusInvited  SpireServerStatus = "invited"
)

// Defines values for TrustBundleStatus.
const (
	Active   TrustBundleStatus = "active"
	Inactive TrustBundleStatus = "inactive"
	ToDelete TrustBundleStatus = "to_delete"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// FederationGroup defines model for FederationGroup.
type FederationGroup struct {
	Id     int64                  `json:"id"`
	Name   string                 `json:"name"`
	Orgid  int64                  `json:"orgid"`
	Status *FederationGroupStatus `json:"status,omitempty"`
}

// FederationGroupStatus defines model for FederationGroup.Status.
type FederationGroupStatus string

// FederationGroupMembership defines model for FederationGroupMembership.
type FederationGroupMembership struct {
	FederationGroupId int64                           `json:"federationGroupId"`
	Id                *int64                          `json:"id,omitempty"`
	SpireServerId     int64                           `json:"spireServerId"`
	Status            FederationGroupMembershipStatus `json:"status"`
}

// FederationGroupMembershipStatus defines model for FederationGroupMembership.Status.
type FederationGroupMembershipStatus string

// FederationRelationship defines model for FederationRelationship.
type FederationRelationship struct {
	FederationGroupId   int64                         `json:"federationGroupId"`
	Id                  int64                         `json:"id"`
	SpireServer1        int64                         `json:"spireServer1"`
	SpireServer1Consent *string                       `json:"spireServer1Consent,omitempty"`
	SpireServer2        int64                         `json:"spireServer2"`
	SpireServer2Consent *string                       `json:"spireServer2Consent,omitempty"`
	Status              *FederationRelationshipStatus `json:"status,omitempty"`
}

// FederationRelationshipStatus defines model for FederationRelationship.Status.
type FederationRelationshipStatus string

// Organization defines model for Organization.
type Organization struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// SpireServer defines model for SpireServer.
type SpireServer struct {
	Description string            `json:"description"`
	Id          int64             `json:"id"`
	Status      SpireServerStatus `json:"status"`
	TrustDomain *string           `json:"trustDomain,omitempty"`
}

// SpireServerStatus defines model for SpireServer.Status.
type SpireServerStatus string

// TrustBundle defines model for TrustBundle.
type TrustBundle struct {
	Bundle      string             `json:"bundle"`
	Id          int64              `json:"id"`
	Status      *TrustBundleStatus `json:"status,omitempty"`
	TrustDomain *string            `json:"trustDomain,omitempty"`
}

// TrustBundleStatus defines model for TrustBundle.Status.
type TrustBundleStatus string

// GetFederationGroupMembershipsParams defines parameters for GetFederationGroupMemberships.
type GetFederationGroupMembershipsParams struct {
	// filter federation groups memberships by orgId
	OrgId *string `form:"orgId,omitempty" json:"orgId,omitempty"`

	// filter federation groups memberships by orgname
	Orgname *string `form:"orgname,omitempty" json:"orgname,omitempty"`

	// filter memberships by trust domain (SpireSever)
	TrustDomain *string `form:"trustDomain,omitempty" json:"trustDomain,omitempty"`

	// filter memberships by status
	Status *GetFederationGroupMembershipsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetFederationGroupMembershipsParamsStatus defines parameters for GetFederationGroupMemberships.
type GetFederationGroupMembershipsParamsStatus string

// GetFederationGroupsParams defines parameters for GetFederationGroups.
type GetFederationGroupsParams struct {
	// filter federation groups by orgId
	OrgId *string `form:"orgId,omitempty" json:"orgId,omitempty"`

	// filter federation groups by orgname
	Orgname *string `form:"orgname,omitempty" json:"orgname,omitempty"`

	// filter organizations by federation group name
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// GetFederationRelationshipsParams defines parameters for GetFederationRelationships.
type GetFederationRelationshipsParams struct {
	// filter federation groups memberships by orgId
	OrgId *string `form:"orgId,omitempty" json:"orgId,omitempty"`

	// filter federation groups memberships by orgname
	Orgname *string `form:"orgname,omitempty" json:"orgname,omitempty"`

	// filter memberships by trust domain (SpireSever)
	TrustDomain *string `form:"trustDomain,omitempty" json:"trustDomain,omitempty"`

	// filter memberships by status
	Status *GetFederationRelationshipsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetFederationRelationshipsParamsStatus defines parameters for GetFederationRelationships.
type GetFederationRelationshipsParamsStatus string

// GetOrganizationsParams defines parameters for GetOrganizations.
type GetOrganizationsParams struct {
	// filter organizations by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// GetSpireServersParams defines parameters for GetSpireServers.
type GetSpireServersParams struct {
	// filter SpireServers by trust domain
	TrustDomain *string `form:"trustDomain,omitempty" json:"trustDomain,omitempty"`

	// filter SpireServers by status
	Status *GetSpireServersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetSpireServersParamsStatus defines parameters for GetSpireServers.
type GetSpireServersParamsStatus string

// CreateSpireServerJSONBody defines parameters for CreateSpireServer.
type CreateSpireServerJSONBody = SpireServer

// CreateSpireServerJSONRequestBody defines body for CreateSpireServer for application/json ContentType.
type CreateSpireServerJSONRequestBody = CreateSpireServerJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /federationGroupMemberships)
	GetFederationGroupMemberships(ctx echo.Context, params GetFederationGroupMembershipsParams) error

	// (POST /federationGroupMemberships)
	CreateFederationGroupMembership(ctx echo.Context) error

	// (DELETE /federationGroupMemberships/{membershipID})
	DeletefederationGroupMembership(ctx echo.Context, membershipID int64) error

	// (GET /federationGroupMemberships/{membershipID})
	GetFederationGroupMembershipbyID(ctx echo.Context, membershipID int64) error

	// (PUT /federationGroupMemberships/{membershipID})
	UpdatefederationGroupMembership(ctx echo.Context, membershipID int64) error

	// (GET /federationGroups)
	GetFederationGroups(ctx echo.Context, params GetFederationGroupsParams) error

	// (POST /federationGroups)
	CreateFederationGroup(ctx echo.Context) error

	// (DELETE /federationGroups/{federationGroupID})
	DeletefederationGroup(ctx echo.Context, federationGroupID int64) error

	// (GET /federationGroups/{federationGroupID})
	GetFederationGroupbyID(ctx echo.Context, federationGroupID int64) error

	// (PUT /federationGroups/{federationGroupID})
	UpdatefederationGroup(ctx echo.Context, federationGroupID int64) error

	// (GET /federationRelationships)
	GetFederationRelationships(ctx echo.Context, params GetFederationRelationshipsParams) error

	// (POST /federationRelationships)
	CreateFederationRelationship(ctx echo.Context) error

	// (GET /federationRelationships/{relationshipID})
	GetFederationRelationshipbyID(ctx echo.Context, relationshipID int64) error

	// (PUT /federationRelationships/{relationshipID})
	UpdateFederationRelationshipship(ctx echo.Context, relationshipID int64) error

	// (GET /organizations)
	GetOrganizations(ctx echo.Context, params GetOrganizationsParams) error

	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error

	// (DELETE /organizations/{orgID})
	DeleteOrganization(ctx echo.Context, orgID int64) error

	// (GET /organizations/{orgID})
	GetOrgbyID(ctx echo.Context, orgID int64) error

	// (PUT /organizations/{orgID})
	UpdateOrganizaion(ctx echo.Context, orgID int64) error

	// (GET /spireServers)
	GetSpireServers(ctx echo.Context, params GetSpireServersParams) error

	// (POST /spireServers)
	CreateSpireServer(ctx echo.Context) error

	// (DELETE /spireServers/{spireServerId})
	DeleteSpireServer(ctx echo.Context, spireServerId int64) error

	// (PUT /spireServers/{spireServerId})
	UpdateSpireServer(ctx echo.Context, spireServerId int64) error

	// (PUT /trustBundles/{trustBundleId})
	UpdateTrustBundle(ctx echo.Context, trustBundleId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFederationGroupMemberships converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationGroupMemberships(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFederationGroupMembershipsParams
	// ------------- Optional query parameter "orgId" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgId", ctx.QueryParams(), &params.OrgId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Optional query parameter "orgname" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgname", ctx.QueryParams(), &params.Orgname)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgname: %s", err))
	}

	// ------------- Optional query parameter "trustDomain" -------------

	err = runtime.BindQueryParameter("form", true, false, "trustDomain", ctx.QueryParams(), &params.TrustDomain)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trustDomain: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationGroupMemberships(ctx, params)
	return err
}

// CreateFederationGroupMembership converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFederationGroupMembership(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateFederationGroupMembership(ctx)
	return err
}

// DeletefederationGroupMembership converts echo context to params.
func (w *ServerInterfaceWrapper) DeletefederationGroupMembership(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "membershipID" -------------
	var membershipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "membershipID", runtime.ParamLocationPath, ctx.Param("membershipID"), &membershipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter membershipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletefederationGroupMembership(ctx, membershipID)
	return err
}

// GetFederationGroupMembershipbyID converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationGroupMembershipbyID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "membershipID" -------------
	var membershipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "membershipID", runtime.ParamLocationPath, ctx.Param("membershipID"), &membershipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter membershipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationGroupMembershipbyID(ctx, membershipID)
	return err
}

// UpdatefederationGroupMembership converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatefederationGroupMembership(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "membershipID" -------------
	var membershipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "membershipID", runtime.ParamLocationPath, ctx.Param("membershipID"), &membershipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter membershipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatefederationGroupMembership(ctx, membershipID)
	return err
}

// GetFederationGroups converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationGroups(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFederationGroupsParams
	// ------------- Optional query parameter "orgId" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgId", ctx.QueryParams(), &params.OrgId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Optional query parameter "orgname" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgname", ctx.QueryParams(), &params.Orgname)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgname: %s", err))
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationGroups(ctx, params)
	return err
}

// CreateFederationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFederationGroup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateFederationGroup(ctx)
	return err
}

// DeletefederationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) DeletefederationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "federationGroupID" -------------
	var federationGroupID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "federationGroupID", runtime.ParamLocationPath, ctx.Param("federationGroupID"), &federationGroupID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter federationGroupID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletefederationGroup(ctx, federationGroupID)
	return err
}

// GetFederationGroupbyID converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationGroupbyID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "federationGroupID" -------------
	var federationGroupID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "federationGroupID", runtime.ParamLocationPath, ctx.Param("federationGroupID"), &federationGroupID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter federationGroupID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationGroupbyID(ctx, federationGroupID)
	return err
}

// UpdatefederationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatefederationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "federationGroupID" -------------
	var federationGroupID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "federationGroupID", runtime.ParamLocationPath, ctx.Param("federationGroupID"), &federationGroupID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter federationGroupID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatefederationGroup(ctx, federationGroupID)
	return err
}

// GetFederationRelationships converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationRelationships(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFederationRelationshipsParams
	// ------------- Optional query parameter "orgId" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgId", ctx.QueryParams(), &params.OrgId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Optional query parameter "orgname" -------------

	err = runtime.BindQueryParameter("form", true, false, "orgname", ctx.QueryParams(), &params.Orgname)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgname: %s", err))
	}

	// ------------- Optional query parameter "trustDomain" -------------

	err = runtime.BindQueryParameter("form", true, false, "trustDomain", ctx.QueryParams(), &params.TrustDomain)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trustDomain: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationRelationships(ctx, params)
	return err
}

// CreateFederationRelationship converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFederationRelationship(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateFederationRelationship(ctx)
	return err
}

// GetFederationRelationshipbyID converts echo context to params.
func (w *ServerInterfaceWrapper) GetFederationRelationshipbyID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "relationshipID" -------------
	var relationshipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "relationshipID", runtime.ParamLocationPath, ctx.Param("relationshipID"), &relationshipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relationshipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFederationRelationshipbyID(ctx, relationshipID)
	return err
}

// UpdateFederationRelationshipship converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateFederationRelationshipship(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "relationshipID" -------------
	var relationshipID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "relationshipID", runtime.ParamLocationPath, ctx.Param("relationshipID"), &relationshipID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relationshipID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateFederationRelationshipship(ctx, relationshipID)
	return err
}

// GetOrganizations converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizations(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrganizationsParams
	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOrganizations(ctx, params)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgID" -------------
	var orgID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "orgID", runtime.ParamLocationPath, ctx.Param("orgID"), &orgID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteOrganization(ctx, orgID)
	return err
}

// GetOrgbyID converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrgbyID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgID" -------------
	var orgID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "orgID", runtime.ParamLocationPath, ctx.Param("orgID"), &orgID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOrgbyID(ctx, orgID)
	return err
}

// UpdateOrganizaion converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganizaion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgID" -------------
	var orgID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "orgID", runtime.ParamLocationPath, ctx.Param("orgID"), &orgID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateOrganizaion(ctx, orgID)
	return err
}

// GetSpireServers converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpireServers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpireServersParams
	// ------------- Optional query parameter "trustDomain" -------------

	err = runtime.BindQueryParameter("form", true, false, "trustDomain", ctx.QueryParams(), &params.TrustDomain)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trustDomain: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSpireServers(ctx, params)
	return err
}

// CreateSpireServer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSpireServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateSpireServer(ctx)
	return err
}

// DeleteSpireServer converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSpireServer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spireServerId" -------------
	var spireServerId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "spireServerId", runtime.ParamLocationPath, ctx.Param("spireServerId"), &spireServerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spireServerId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteSpireServer(ctx, spireServerId)
	return err
}

// UpdateSpireServer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSpireServer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spireServerId" -------------
	var spireServerId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "spireServerId", runtime.ParamLocationPath, ctx.Param("spireServerId"), &spireServerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spireServerId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateSpireServer(ctx, spireServerId)
	return err
}

// UpdateTrustBundle converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTrustBundle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trustBundleId" -------------
	var trustBundleId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "trustBundleId", runtime.ParamLocationPath, ctx.Param("trustBundleId"), &trustBundleId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trustBundleId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateTrustBundle(ctx, trustBundleId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/federationGroupMemberships", wrapper.GetFederationGroupMemberships)
	router.POST(baseURL+"/federationGroupMemberships", wrapper.CreateFederationGroupMembership)
	router.DELETE(baseURL+"/federationGroupMemberships/:membershipID", wrapper.DeletefederationGroupMembership)
	router.GET(baseURL+"/federationGroupMemberships/:membershipID", wrapper.GetFederationGroupMembershipbyID)
	router.PUT(baseURL+"/federationGroupMemberships/:membershipID", wrapper.UpdatefederationGroupMembership)
	router.GET(baseURL+"/federationGroups", wrapper.GetFederationGroups)
	router.POST(baseURL+"/federationGroups", wrapper.CreateFederationGroup)
	router.DELETE(baseURL+"/federationGroups/:federationGroupID", wrapper.DeletefederationGroup)
	router.GET(baseURL+"/federationGroups/:federationGroupID", wrapper.GetFederationGroupbyID)
	router.PUT(baseURL+"/federationGroups/:federationGroupID", wrapper.UpdatefederationGroup)
	router.GET(baseURL+"/federationRelationships", wrapper.GetFederationRelationships)
	router.POST(baseURL+"/federationRelationships", wrapper.CreateFederationRelationship)
	router.GET(baseURL+"/federationRelationships/:relationshipID", wrapper.GetFederationRelationshipbyID)
	router.PUT(baseURL+"/federationRelationships/:relationshipID", wrapper.UpdateFederationRelationshipship)
	router.GET(baseURL+"/organizations", wrapper.GetOrganizations)
	router.POST(baseURL+"/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/organizations/:orgID", wrapper.DeleteOrganization)
	router.GET(baseURL+"/organizations/:orgID", wrapper.GetOrgbyID)
	router.PUT(baseURL+"/organizations/:orgID", wrapper.UpdateOrganizaion)
	router.GET(baseURL+"/spireServers", wrapper.GetSpireServers)
	router.POST(baseURL+"/spireServers", wrapper.CreateSpireServer)
	router.DELETE(baseURL+"/spireServers/:spireServerId", wrapper.DeleteSpireServer)
	router.PUT(baseURL+"/spireServers/:spireServerId", wrapper.UpdateSpireServer)
	router.PUT(baseURL+"/trustBundles/:trustBundleId", wrapper.UpdateTrustBundle)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb32/bOBL+VwjeAXcHKHWaFoeF39omDfKwSJHsPhXBgrbGDguZVEkqadbw/74gKVvU",
	"L4pWYtlu8xTHIsVvZj7OfENZSzzli5QzYEri8RLL6T0siPl4IQQX+kMqeApCUTBfT3kM+u+MiwVReIwp",
	"U+/OcITVUwr2X5iDwKsIL0BKMjej84tSCcrmeLWKsIDvGRUQ4/FXe89i/N3mZnzyDaZK3+szxCCIopxd",
	"Cp6ldVw0rqL6//tGVIwsygbkoKIqyAhzMQ++rVREZQYJsGyhraKMTBV90JblH+6i7lUrrqExXuPIoQd4",
	"53dYTEDIe9rgp1l56FWofeGOSKmAWxAPIK76O2/juo0X77pcVV44arB0s5DfhzeQmL/7d+DbHlM+cSaB",
	"qUCKOzPPtl/sbMvFAsKsPz5QBXF3wGlrlF0PVmxsCv21mBNG/zZ3GSKzNNnRurdvC/R1bDHIqaDpGnhA",
	"DJ6V0GxgoqDdGWElMqnO+YJQ1tst5h6xvUdUMte7mf/Q0z5mLE6g7rTJ5vsNpMmTAvnC7mrituJ/xZCA",
	"Gsphual1F+m5lM14jUT4FhTiM/Thy5VEiqMJoExCjCZP6JIkJBYUEkTiBWVUKrvxzLgYZpQBIixGU85m",
	"dJ4JQOoe0ETQeA4RWtiiFJkhwkmxxu9U6Yjg2y9XNxfoo5mCTpwV7QbQqHCEH0BIC/btm9M3p6ZUp8BI",
	"SvEYvzNfRTgl6t7EYzRrq47m8hxU3Qk3oDLBJCJJgorpaK7ny7UpOXZNLXNZlwJ8Cepz+3oaliALUCAk",
	"Hn+tLjujiQLhX1FHgou5SXSaJ/h7BuJpnUHGeH3NSjkfewsaPQOHWbUVSX61AUs7p1vAVJY2PEeW6Oi/",
	"eZJ8APG/FjDu3toJoDwBNK++uVgs7JWJVQx3eqfLVFdbQ9qz01MrxpnKyy9J04ROTbBG36QtB8ViVMHC",
	"TPy3gBke43+NCt0/ykX/qF1FrjaIiBDkyaaPslPmoFDlBtpDkN/iPxKtDcBm7oxkidrKBh9026w0wMoY",
	"/EhhqiBGUIxJuWzY9B+k5FNKFCCCnKqrsxtxbEO2A6lu/E8CiIJ2H9pcDVJ95PGTz3CyleWeoNW9cZHA",
	"Qs/WCV7n5uoGdzhtrI5j7JYYJTJY1Zj49sWiuJUt1YC42Kc6FvrKwXBuFfnq0GhZgL86X1lqGplQI6n9",
	"HhE0q2+2gmplap6bOTMPNb1V6Squ8+WygS455DwD6vpbJEDXvhqnQorVRmo15ML3dTcxjtZB3n+6aZQY",
	"OmHGRBE04wJxBtXsuZWymDwZt/YMo5V5ApSg8ADxHiJ4uqsc0laqqi64Oj+wCpU1UCZLY9K09wseaCFi",
	"wlOmzp9m4s4TgMU3DH1CSumPk8fHxxN9w5NMJMCmPIZ4R+UohyDDPKW7KuOsGK+OLJ01VLKefVRAhuvf",
	"Me2zSxq4M+LO8ZVZvCbrPFB64NhHM9KzBTmGtsM2DoggBo+10IW1GQM1F71aiv33EUHdw1G0DHK0rJ53",
	"9+sWwlqEZylKXzdQM+K1JXihlmCARmD3wXvtBp7TDWzTAzyLKj65vxOSDK/5+yj9n0ne35Se02yp8qsP",
	"eTy566Yy9PUpyetTko6nJN4fCgzcopR+MbJ1p1LaKMfTsUhEGVUkQXliNqrFEMg+dUbwY3pP2BzQBNQj",
	"AEPqkbsPViSyoUSUmUQqyQK2b4BKvt95H1SO9FbtkBvl/XZFXUa0UPPge6RSFRktXex5n7QD2e0uOoD6",
	"Lht1FNK7i26/6nl8i/zpdyBfSy8+df7yJBpUmncR6pc6iy+d/gZJ9OvSjIbkVh0QosZrh9BHeOZc+h1o",
	"oIxz7T6602YXfIvQui4P2Ym8Kvu9W1S5sPehpLrwutcPVDSVtutoqdvhsJNk5ieNPUeukCawllXD6jtB",
	"NoBfT40b5as3QDa9bydUq4HpVqm7Cc/pYDv4wDO7T4wWG1RHy6c/r4tx/bngk5kvxoIB1GUXI6qakov5",
	"TyAenVdjwrSjNt09wmnKL5XrIeqxdCpUObcc7KiyCqL/WeX6PZnD+W23+xZRoLJ13XEA+e9iK2Xr2tss",
	"bMsjAnXtVlaVfO5Xtfa9F1n83nxgRdsB1f01/GHqWTeRjZalV0HDfiDhI4wVteURgeWyGlifpq2+wPpr",
	"adtGUWOFirSPB0zG1Y71R8vOeZFo+cTNi0drAJHTsc2rGqfFHasdCvMOhAdYl0ppSBXvncrR0vkvT0Mt",
	"JE84iRFB7lurzawujwhktRVT+UO5DlaXIB8Jq12nBLC6xR27ZHUHQs1qF9VBsXoVYbluEL4ucSYSPMb3",
	"SqXj0SjhU5Lcc6nG787OTn8b4dXd6p8AAAD//zpRUyVTRAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
