// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlite

import (
	"context"
)

type Querier interface {
	CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error)
	CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error)
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error)
	CreateTrustDomain(ctx context.Context, arg CreateTrustDomainParams) (TrustDomain, error)
	DeleteBundle(ctx context.Context, id string) error
	DeleteJoinToken(ctx context.Context, id string) error
	DeleteRelationship(ctx context.Context, id string) error
	DeleteTrustDomain(ctx context.Context, id string) error
	FindBundleByID(ctx context.Context, id string) (Bundle, error)
	FindBundleByTrustDomainID(ctx context.Context, trustDomainID string) (Bundle, error)
	FindJoinToken(ctx context.Context, token string) (JoinToken, error)
	FindJoinTokenByID(ctx context.Context, id string) (JoinToken, error)
	FindJoinTokensByTrustDomainID(ctx context.Context, trustDomainID string) ([]JoinToken, error)
	FindRelationshipByID(ctx context.Context, id string) (Relationship, error)
	FindRelationshipsByTrustDomainID(ctx context.Context, arg FindRelationshipsByTrustDomainIDParams) ([]Relationship, error)
	FindTrustDomainByID(ctx context.Context, id string) (TrustDomain, error)
	FindTrustDomainByName(ctx context.Context, name string) (TrustDomain, error)
	ListBundles(ctx context.Context) ([]Bundle, error)
	ListJoinTokens(ctx context.Context) ([]JoinToken, error)
	ListRelationships(ctx context.Context) ([]Relationship, error)
	ListTrustDomains(ctx context.Context) ([]TrustDomain, error)
	UpdateBundle(ctx context.Context, arg UpdateBundleParams) (Bundle, error)
	UpdateJoinToken(ctx context.Context, arg UpdateJoinTokenParams) (JoinToken, error)
	UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (Relationship, error)
	UpdateTrustDomain(ctx context.Context, arg UpdateTrustDomainParams) (TrustDomain, error)
}

var _ Querier = (*Queries)(nil)
