name: PR Build

on:
  pull_request: {}

permissions: read-all

jobs:
  analysis:
    name: PR Build
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout code"
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
   
    - name: "Setup Go"
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: 'go.mod'

    - name: "Lint"
      uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v6.5.1
      with:
        version: v1.57
        args: --timeout 3m0s

    - name: "Unit test"
      run: make test
