name: PR Build

on:
  pull_request: {}

permissions: read-all

jobs:
  analysis:
    name: PR Build
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout code"
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
   
    - name: "Setup Go"
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: 'go.mod'

    - name: "Lint"
      uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5.3.0
      with:
        version: v1.57
        args: --timeout 3m0s

    - name: "Unit test"
      run: make test
