name: PR Build

on:
  pull_request: {}

permissions: read-all

jobs:
  analysis:
    name: PR Build
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout code"
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
   
    - name: "Setup Go"
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: 'go.mod'

    - name: "Lint"
      uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
      with:
        version: v1.48
        args: --timeout 3m0s

    - name: "Unit test"
      run: make test
