name: Release Build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger this workflow when a new vX.Y.Z tag is pushed
env:
  GO_VERSION: 1.20.3

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

      - name: Build Artifacts
        run: ./.github/workflows/scripts/build_artifacts.sh

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            galadriel-*-linux-*-glibc.tar.gz
            galadriel-*-linux-*-glibc.tar.gz.sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
